### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by MohamedCK** [MohamedCK/space-traveler-s-hub#25]
[A Link to the GitHub Project](https://github.com/MohamedCK/space-traveler-s-hub/projects/1) 

- In this react group Project we are a team of 2 ( @RichardChileya  and @MohamedCK  )

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- Kindly point the link to the kanban board, it currently points to the project README.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MohamedCK** [comment]
Hi @brytebee  thank's for pointing that out we updated :smile:

**Comment by MohamedCK** [comment]
Project ready to start
